// ReSharper disable IdentifierTypo
namespace TSLab.DataSource
{
    public enum Broker
    {
        Undefined = 0,
        Bittrex,
        Bitfinex,
        BinanceSpot,
        Deribit,
        AlorDemo,
        AlorMicex,
        AlorForts,
        AlorDemoForts,
        Huobi,
        BinanceFutures,
        Bitmex,
        BinanceFutCoin,
        OkxSpot,
        OkxMargin,
        OkxPerpSwap,
        OkxFutures,
        ByBitSpot,
        ByBitPerpUsdt,
        ByBitPerpInverse,
        ByBitFutInverse,
        AlorDemoCurrency,
        AlorOpen,
        Bitmex_USDT,
        BinanceMargin,
        BinanceUSA,
        Lmax,
        InteractiveBrokers,
        Iqfeed,
        Rithmic,
        Quik,
        QuikLua,
        QuikLua2,
        NetInvestor,
        RicomTrust,
        Rts,
        RtsAlor,
        SmartCom,
        Tinkoff,
        Tinkoff2,
        Transaq,
        TransaqAdd,
        TransaqHft,
        TransaqJust2Trade,
        TransaqSpc,
        TransaqDemo,
        RtsItinvest,
        RtsOpen,
        QuikBcs,
        QuikOpen,

        Unknown = 999
	}
}
